using System.Diagnostics;
using System.Management;
using FlaUI.Core.AutomationElements;
using FlaUI.Core.WindowsAPI;
using FlaUI.UIA3;
using OpenQA.Selenium.Chrome;
using Polly;

namespace Flanium;

public class WinEvents
{
    public class Id
    {
        public static int GetDriverProcessId(ChromeDriverService driverService)
        {
            //Get all the childs generated by the driver like conhost, chrome.exe...
            var mos = new ManagementObjectSearcher(
                $"Select * From Win32_Process Where ParentProcessID={driverService.ProcessId}");
            foreach (var mo in mos.Get())
            {
                var processId = Convert.ToInt32(mo["ProcessID"]);
                return processId;
            }

            return 0;
        }

        public static Window GetWindowByProcessId(int processId)
        {
            var automation = new UIA3Automation();
            var allProcesses = Process.GetProcesses();
            //loop through processes
            foreach (var item in allProcesses)
                if (item.Id == processId)
                    return automation.FromHandle(item.MainWindowHandle).AsWindow();

            return null;
        }

    }
    public class Linq
    {
        public static Window GetWindowByLinq(Func<AutomationElement, bool> linq)
        {
            var automation = new UIA3Automation();
            var desktop = automation.GetDesktop();
            var window = desktop.FindAllChildren().Single(linq).AsWindow();
            return window;
        }
        public static List<Window> GetWindowsByLinq(Func<AutomationElement, bool> linq)
        {
            var automation = new UIA3Automation();
            var desktop = automation.GetDesktop();
            var windows = desktop.FindAllChildren().Where(linq).ToList();

            return windows.Select(window => window.AsWindow()).ToList();
        }

        public static AutomationElement FindElementByLinq(Window window, Func<AutomationElement, bool> linq,
            int retries = 15, double retryInterval = 1)
        {
            var retryFind = Policy.HandleResult<AutomationElement>(result => result == null)
                .WaitAndRetry(retries, interval => TimeSpan.FromSeconds(retryInterval));
            var retryFindResult = retryFind.Execute(() =>
            {
                try
                {
                    var allChildrenList = window.FindAllChildren().ToList();

                    foreach (var child in allChildrenList)
                        try
                        {
                            return child.FindAllDescendants().Single(linq);
                        }
                        catch (Exception e)
                        {
                            return null;
                        }
                }
                catch (Exception e)
                {
                    return null;
                }

                return null;
            });


            return retryFindResult;
        }

        public static List<AutomationElement> FindElementsByLinq(Window window, Func<AutomationElement, bool> linq,
            int retries = 15, double retryInterval = 1)
        {
            var retryFind = Policy.HandleResult<List<AutomationElement>>(result => result == null)
                .WaitAndRetry(retries, interval => TimeSpan.FromSeconds(retryInterval));
            var retryFindResult = retryFind.Execute(() =>
            {
                try
                {
                    return window.FindAllDescendants().Where(linq).ToList();
                }
                catch (Exception e)
                {
                    return null;
                }
            });

            return retryFindResult;
        }

        public static AutomationElement FindElementInElementByLinq(AutomationElement element,
            Func<AutomationElement, bool> linq, int retries = 15, double retryInterval = 1)
        {
            var retryFind = Policy.HandleResult<AutomationElement>(result => result == null)
                .WaitAndRetry(retries, interval => TimeSpan.FromSeconds(retryInterval));
            var retryFindResult = retryFind.Execute(() =>
            {
                try
                {
                    return element.FindAllDescendants().Single(linq);
                }
                catch (Exception e)
                {
                    return null;
                }
            });

            return retryFindResult;
        }

        public static List<AutomationElement> FindElementsInElementByLinq(AutomationElement element,
            Func<AutomationElement, bool> linq, int retries = 15, double retryInterval = 1)
        {
            var retryFind = Policy.HandleResult<List<AutomationElement>>(result => result == null)
                .WaitAndRetry(retries, interval => TimeSpan.FromSeconds(retryInterval));
            var retryFindResult = retryFind.Execute(() =>
            {
                try
                {
                    return element.FindAllDescendants().Where(linq).ToList();
                }
                catch (Exception e)
                {
                    return null;
                }
            });

            return retryFindResult;
        }
    }


    public class XPath
    {
        public static Window GetWindowByXPath(string xPath)
        {
            var automation = new UIA3Automation();
            var desktop = automation.GetDesktop();
            var window = desktop.FindFirstByXPath(xPath).AsWindow();
            return window;
        }

        public static List<Window> GetWindowsByXPath(string xPath)
        {
            var automation = new UIA3Automation();
            var desktop = automation.GetDesktop();
            var window = desktop.FindAllByXPath(xPath);
            return window.Select(w => w.AsWindow()).ToList();
        }

        public static AutomationElement FindElementByXPath(Window window, string xPath)
        {
            return window.FindFirstByXPath(xPath);
        }

        public static List<AutomationElement> FindElementsByXPath(Window window, string xPath)
        {

                var allChildrenList = window.FindAllByXPath(xPath).ToList();
                
            return allChildrenList;
        }

        public static AutomationElement FindElementInElementByXPath(AutomationElement element, string xPath)
        {
            return element.FindFirstByXPath(xPath);
        }

        public static List<AutomationElement> FindElementsInElementByXPath(AutomationElement element, string xPath)
        {

                var allChildrenList = element.FindAllByXPath(xPath).ToList();

            return allChildrenList;
        }
    }

    public class Actions
    {
        
        public static string GetText(AutomationElement element, int retries = 15, double retryInterval = 1)
        {
            var retryGetText = Policy.HandleResult<string>(result => result == null)
                .WaitAndRetry(retries, interval => TimeSpan.FromSeconds(retryInterval));
            var retryGetTextResult = retryGetText.Execute(() =>
            {
                try
                {
                    return element.AsTextBox().Text;
                }
                catch (Exception e)
                {
                    return null;
                }
            });
            return retryGetTextResult;
        }
        public static bool SendText(AutomationElement element, string text, bool events = false, int retries = 15,
            double retryInterval = 1)
        {
            if (element != null)
            {
                if (events == false)
                {
                    var retryClick = Policy.HandleResult<bool>(result => result == true)
                        .WaitAndRetry(retries, interval => TimeSpan.FromSeconds(retryInterval));
                    var retryResult = retryClick.Execute(() =>
                    {
                        try
                        {
                            element.AsTextBox().Text = text;

                            while (element.AsTextBox().Text != text) Thread.Sleep(250);
                        }
                        catch (Exception e)
                        {
                            // ignored
                        }

                        return false;
                    });

                    return retryResult;
                }
                else
                {
                    var retryClick = Policy.HandleResult<bool>(result => result == true)
                        .WaitAndRetry(retries, interval => TimeSpan.FromSeconds(retryInterval));
                    var retryResult = retryClick.Execute(() =>
                    {
                        try
                        {
                            element.AsTextBox().Enter(text);

                            while (element.AsTextBox().Text != text) Thread.Sleep(250);
                        }
                        catch (Exception e)
                        {
                            // ignored
                        }

                        return false;
                    });

                    return retryResult;
                }
            }

            return false;
        }

        public static bool Click(AutomationElement element, bool invoke = false, int retries = 15,
            double retryInterval = 1)
        {
            if (element != null)
            {
                if (invoke == false)
                {
                    var retryClick = Policy.HandleResult<bool>(result => result == true)
                        .WaitAndRetry(retries, interval => TimeSpan.FromSeconds(retryInterval));
                    var retryResult = retryClick.Execute(() =>
                    {
                        try
                        {
                            element.Click();
                            Thread.Sleep(100);
                        }
                        catch (Exception e)
                        {
                            // ignored
                        }

                        return false;
                    });

                    return retryResult;
                }
                else
                {
                    var retryClick = Policy.HandleResult<bool>(result => result == true)
                        .WaitAndRetry(retries, interval => TimeSpan.FromSeconds(retryInterval));
                    var retryResult = retryClick.Execute(() =>
                    {
                        try
                        {
                            element.AsButton().Invoke();
                            Thread.Sleep(100);
                        }
                        catch (Exception e)
                        {
                            // ignored
                        }

                        return false;
                    });

                    return retryResult;
                }
            }

            return false;
        }

        public static bool DoubleClick(AutomationElement element, bool invoke = false, int retries = 15,
            double retryInterval = 1)
        {
            if (element != null)
            {
                if (invoke == false)
                {
                    var retryClick = Policy.HandleResult<bool>(result => result == true)
                        .WaitAndRetry(retries, interval => TimeSpan.FromSeconds(retryInterval));
                    var retryResult = retryClick.Execute(() =>
                    {
                        try
                        {
                            element.DoubleClick();
                            Thread.Sleep(100);
                        }
                        catch (Exception e)
                        {
                            // ignored
                        }

                        return false;
                    });

                    return retryResult;
                }
                else
                {
                    var retryClick = Policy.HandleResult<bool>(result => result == true)
                        .WaitAndRetry(retries, interval => TimeSpan.FromSeconds(retryInterval));
                    var retryResult = retryClick.Execute(() =>
                    {
                        try
                        {
                            element.AsButton().Invoke();
                            Thread.Sleep(100);
                        }
                        catch (Exception e)
                        {
                            // ignored
                        }

                        return false;
                    });

                    return retryResult;
                }
            }

            return false;
        }

        public static bool RightClick(AutomationElement element, bool invoke = false, int retries = 15,
            double retryInterval = 1)
        {
            if (element != null)
            {
                if (invoke == false)
                {
                    var retryClick = Policy.HandleResult<bool>(result => result == true)
                        .WaitAndRetry(retries, interval => TimeSpan.FromSeconds(retryInterval));
                    var retryResult = retryClick.Execute(() =>
                    {
                        try
                        {
                            element.RightClick();
                            Thread.Sleep(100);
                        }
                        catch (Exception e)
                        {
                            // ignored
                        }

                        return false;
                    });

                    return retryResult;
                }
            }

            return false;
        }

        public static void SendKeys(VirtualKeyShort keyShort)
        {
            FlaUI.Core.Input.Keyboard.Press(keyShort);
        }
    }
}